version: '2'

services:
  db:
    image: 'bitnami/mysql:latest'
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/mysql:/bitnami/mysql/data